export const TWELVE_MONTH_ANALYSIS_CONFIGS = {
  '12-month-analysis-payroll': {
    worksheetKey: 'twelve-month-analysis-payroll',
    title: '12 MONTH ANALYSIS - PAYROLL',
    description: 'Monthly payroll expense detail (wages, benefits, taxes).',
    analysisType: 'payroll',
    categories: [
      { value: 'wages', label: 'Wages & Salaries' },
      { value: 'benefits', label: 'Benefits' },
      { value: 'payroll_taxes', label: 'Payroll Taxes' },
      { value: 'contractors', label: 'Contractors' },
      { value: 'other_payroll', label: 'Other Payroll' },
    ],
    plMapCategory: 'opex_payroll',
  },
  '12-month-analysis-direct-labor': {
    worksheetKey: 'twelve-month-analysis-direct-labor',
    title: '12 MONTH ANALYSIS - DIRECT LABOR',
    description: 'Monthly direct labor cost detail for job costing and P&L rollups.',
    analysisType: 'direct_labor',
    categories: [
      { value: 'shop_labor', label: 'Shop Labor' },
      { value: 'field_labor', label: 'Field Labor' },
      { value: 'overtime', label: 'Overtime' },
      { value: 'burden', label: 'Labor Burden' },
      { value: 'other_labor', label: 'Other Direct Labor' },
    ],
    plMapCategory: 'cogs_labor',
  },
  '12-month-analysis-material': {
    worksheetKey: 'twelve-month-analysis-material',
    title: '12 MONTH ANALYSIS - MATERIAL',
    description: 'Monthly materials and supplies expense detail.',
    analysisType: 'material',
    categories: [
      { value: 'raw_material', label: 'Raw Material' },
      { value: 'supplies', label: 'Supplies' },
      { value: 'freight', label: 'Freight' },
      { value: 'waste', label: 'Waste / Shrink' },
      { value: 'other_material', label: 'Other Material' },
    ],
    plMapCategory: 'cogs_material',
  },
  '12-month-analysis-operating-exp': {
    worksheetKey: 'twelve-month-analysis-operating-exp',
    title: '12 MONTH ANALYSIS - OPERATING EXP',
    description: 'Monthly operating expense detail (rent, utilities, insurance, admin).',
    analysisType: 'operating_exp',
    categories: [
      { value: 'rent', label: 'Rent' },
      { value: 'utilities', label: 'Utilities' },
      { value: 'insurance', label: 'Insurance' },
      { value: 'admin', label: 'Administrative' },
      { value: 'other_opex', label: 'Other Operating' },
    ],
    plMapCategory: 'opex',
  },
};
