#!/usr/bin/env python3
"""Regenerate incorporation status markdown from catalog and build list."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
CATALOG = ROOT / "knowledge" / "workbooks" / "worksheet_catalog.json"
OUTPUT = ROOT / "knowledge" / "workbooks" / "not-incorporated-sheets.md"


def main() -> None:
    catalog = json.loads(CATALOG.read_text(encoding="utf-8"))

    integrated: list[str] = []
    planned: list[str] = []
    by_hub: dict[str, list[str]] = {}

    for entry in catalog:
        key = entry["key"]
        name = entry.get("sheetName", key)
        status = entry.get("integrationStatus", "planned")
        hub = entry.get("hubCategory", "financial-analysis")
        description = entry.get("description", "")
        core = entry.get("coreRank")
        meta_bits = [f"`{key}`", hub, status]
        if core is not None:
            meta_bits.append(f"core {core}")
        meta = " · ".join(meta_bits)
        line = f"- **{name}** ({meta})"
        if description:
            line += f" — {description}"

        if status in {"native", "derived", "workbook-port"}:
            integrated.append(line)
        else:
            planned.append(line)

        by_hub.setdefault(hub, [])
        by_hub[hub].append(f"- {name} (`{key}`)")

    lines = [
        "# Worksheet incorporation status",
        "",
        "Auto-generated by `python_engine/tools/generate_incorporation_status.py`.",
        "",
        f"## Integrated ({len(integrated)})",
        "",
        *integrated,
        "",
        f"## Planned ({len(planned)})",
        "",
        *planned,
        "",
        "## By hub category",
        "",
    ]

    for hub in sorted(by_hub):
        lines.append(f"### {hub} ({len(by_hub[hub])})")
        lines.append("")
        lines.extend(by_hub[hub])
        lines.append("")

    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUTPUT}")


if __name__ == "__main__":
    main()
